server:
  port: 9003
  shutdown: graceful # enables graceful shutdown
  netty:
    connection-timeout: 2s # how long to wait for a TCP connection to be established with the server
    idle-timeout: 15s # how long to wait before closing a TCP connection if no data is transferred

spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s # defines a 15 s grace period
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/polardb_order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/polardb_order
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
  config:
    import: "optional:configserver:"
  cloud:
    function:
      definition: dispatchOrder
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched
          group: ${spring.application.name}
        acceptOrder-out-0:
          destination: order-accepted
      rabbit:
        bindings:
          acceptOrder-out-0:
            producer:
              transacted: true
    config:
      uri: http://localhost:9002
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 5000
        multiplier: 1.2

polar:
  catalog-service-uri: "http://localhost:9001"
